version: "3.8"

services:
  frontend:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1

  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: smoothstack
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
