version: "3.8"

services:
  frontend:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      PYTHONPATH: /usr/src/app
      FLASK_APP: app
      FLASK_DEBUG: 1
      MYSQL_DATABASE: smoothstack
      MYSQL_HOST: database
      MYSQL_USER: root
    depends_on:
      - database

  database:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: smoothstack

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
