version: "3.8"

services:
  frontend:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1

  database:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=smoothstack
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
