DROP TABLE IF EXISTS summary;
DROP TABLE IF EXISTS voc;

CREATE TABLE summary (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  time_period TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  calls_offered INT NOT NULL,
  abandoned_after_30 FLOAT NOT NULL,
  fcr FLOAT NOT NULL,
  dsat FLOAT NOT NULL,
  csat FLOAT NOT NULL
);

CREATE TABLE voc (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  time_period TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  promoters INT NOT NULL,
  passives INT NOT NULL,
  detractors INT NOT NULL
);
